### DISCUSSION TITLE
Support managing GitHub organization via CLOWarden

### DISCUSSION THREAD

**Discussion by austinlparker** [cncf/clowarden#250] [Ideas]
Hi! I'm a maintainer of OpenTelemetry, and we're interested in adopting CLOWarden to manage repos, teams, and organization users. I initially thought CLOWarden would be a 'drop-in' solution for us, but it appears that it is not, mostly due to one reason -- CLOWarden expects that organization membership is tied to team membership. In OpenTelemetry, we do not necessarily follow this  -- contributors become org members first, then are added to specific teams as they move up the contributor ladder.

After looking at the way that other projects which use CLOWarden manage their GitHub orgs, I can see the logic in how CLOWarden does it (adding people as external collaborators to a repo, for instance) -- but I am curious, if we decide to maintain our current strategy for managing membership, would y'all be willing to accept a PR that added a new, 'merged' configuration file format that combined the CNCF and Sheriff concepts that we could use to hoist org membership into CLOWarden with? In essence, I'm thinking of something like this for a format --

```
organizaton: foo
members:
  - name: bar
    github: FooBar
    slack: "@foobar"
    website: https://foobar.io
  - name: baz
    github: BazQuuz
    slack: "@bigbaz"
    website: https://bazbutnotbazel.com
repositories:
  - name: my-cool-repo
    teams:
      - team1
    settings:
      has_wiki: true
      is_featured: true
teams:
  - name: team1
    maintainers:
      - bar
    members:
      - baz
// etc, etc.
```
